# tasks file for debian-12-apache-mod-php
---
- name: apache | vhosts | create
  ansible.builtin.template:
    src: "etc/apache2/sites-available/{{ item.template.file }}"
    dest: "/etc/apache2/sites-available/{{ item.name }}"
    mode: '644'
  with_items: "{{ debian_12_apache_mod_php_apache_vhosts_present | default([]) }}"
  notify: reload apache2

- name: apache | vhosts | create (html) directory
  ansible.builtin.file:
    path: "{{ (item.html_dir | default({})).dest | default(item.base_dir.dest ~ '/public_html') }}/"
    state: directory
    owner: "{{ (item.html_dir | default({})).owner | default((item.base_dir | default({})).owner) | default('root') }}"
    group: "{{ (item.html_dir | default({})).group | default((item.html_dir | default({})).owner) | default((item.base_dir | default({})).group) | default((item.base_dir | default({})).owner) | default('root') }}"
    mode: "{{ (item.html_dir | default({})).mode | default((item.base_dir | default({})).mode) | default('0755') }}"
  with_items: "{{ debian_12_apache_mod_php_apache_vhosts_present | default([]) }}"
  when: (item.html_dir | default({})).managed | default(true)

- name: apache | vhosts | create (log) directory
  ansible.builtin.file:
    path: "{{ (item.log_dir | default({})).dest | default(item.base_dir.dest ~ '/log') }}/"
    state: directory
    owner: "{{ (item.log_dir | default({})).owner | default((item.base_dir | default({})).owner) | default('root') }}"
    group: "{{ (item.log_dir | default({})).group | default((item.log_dir | default({})).owner) | default((item.base_dir | default({})).group) | default((item.base_dir | default({})).owner) | default('root') }}"
    mode: "{{ (item.log_dir | default({})).mode | default((item.base_dir | default({})).mode) | default('0755') }}"
  with_items: "{{ debian_12_apache_mod_php_apache_vhosts_present | default([]) }}"
  when: (item.log_dir | default({})).managed | default(true)

- name: apache | vhosts | create .env file
  ansible.builtin.template:
    src: "var/www/localdomain/localhost/.env.j2"
    dest: "{{ item.base_dir.dest | default('~' + item.username | default('www-data')) }}/.env"
    mode: '644'
  with_items: "{{ debian_12_apache_mod_php_apache_vhosts_present | default([]) }}"
  when: item.set_env | default([]) | length > 0
