# tasks file for debian-12-apache-mod-php
---
- name: apache | configuration | update /etc/apache2/ports.conf
  ansible.builtin.template:
    src: etc/apache2/ports.conf.j2
    dest: /etc/apache2/ports.conf
    mode: '644'
  notify: restart apache2
