# tasks file for debian-12-apache-mod-php
---
- name: apache | mods | install
  ansible.builtin.apt:
    name: "{{ debian_12_apache_mod_php_apache_mods_dependencies[item] | default([]) }}"
  with_items: "{{ debian_12_apache_mod_php_apache_mods_present }}"
  notify: reload apache2
