# tasks file for debian-12-apache-mod-php
---
- name: apache | mods | remoteip | update /etc/apache2/mods-available/remoteip.conf
  ansible.builtin.template:
    src: etc/apache2/mods-available/remoteip.conf.j2
    dest: /etc/apache2/mods-available/remoteip.conf
    mode: '644'
  notify: reload apache2
