# tasks file for debian-12-apache-mod-php
---
- name: apache | vhosts | disable
  ansible.builtin.command: a2dissite {{ item.name }}
  args:
    removes: "/etc/apache2/sites-enabled/{{ item.name }}"
  with_items: "{{ debian_12_apache_mod_php_apache_vhosts_absent | default([]) }}"
  notify: reload apache2

- name: apache | vhosts | enable
  ansible.builtin.command: a2ensite {{ item.name }}
  args:
    creates: "/etc/apache2/sites-enabled/{{ item.name }}"
  with_items: "{{ debian_12_apache_mod_php_apache_vhosts_present | default([]) }}"
  notify: reload apache2
