# tasks file for debian-12-apache-mod-php
---
- name: apache | vhosts | cleanup
  ansible.builtin.file:
    state: absent
    path: "/etc/apache2/sites-available/{{ item.name }}"
  with_items: "{{ debian_12_apache_mod_php_apache_vhosts_absent | default([]) }}"
