# tasks file for debian-12-apache-mod-php
---
- name: php | mods | touch priorities
  ansible.builtin.copy:
    content: ''
    dest: "/etc/php/8.2/mods-available/{{ item }}.ini"
    mode: '644'
    force: false
  with_items: "{{ debian_12_apache_mod_php_php_mods_enabled + debian_12_apache_mod_php_php_mods_disabled }}"

- name: php | mods | get priorities
  ansible.builtin.command: sed -ne "s/^;[ ]\?priority=\([0-9]\+\)$/\\1/p" /etc/php/8.2/mods-available/{{ item }}.ini  # noqa command-instead-of-module
  register: debian_12_apache_mod_php_php_module_priorities
  changed_when: false
  with_items: "{{ debian_12_apache_mod_php_php_mods_enabled + debian_12_apache_mod_php_php_mods_disabled }}"

- name: php | mods | disable
  ansible.builtin.command: phpdismod -s apache2 {{ item.item }}
  args:
    removes: "/etc/php/8.2/apache2/conf.d/{{ item.stdout | default(20, true) }}-{{ item.item }}.ini"
  with_items: "{{ debian_12_apache_mod_php_php_module_priorities.results }}"
  when: item.item in debian_12_apache_mod_php_php_mods_disabled
  notify: restart apache2

- name: php | mods | enable
  ansible.builtin.command: phpenmod -s apache2 {{ item.item }}
  args:
    creates: "/etc/php/8.2/apache2/conf.d/{{ item.stdout | default(20, true) }}-{{ item.item }}.ini"
  with_items: "{{ debian_12_apache_mod_php_php_module_priorities.results }}"
  when: item.item in debian_12_apache_mod_php_php_mods_enabled
  notify: restart apache2
