# tasks file for debian-12-apache-mod-php
---
- name: php | mods | install
  ansible.builtin.apt:
    name: "{{ debian_12_apache_mod_php_php_mods_dependencies[item] | default([]) }}"
  with_items: "{{ debian_12_apache_mod_php_php_mods_enabled }}"
  notify: reload apache2
